language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: FtTs3KowiH+dGVpzZoOfXxXJMmfXxW1Vo8Rsb/cjmRuEI6iEIFfKnjCiuStzR9e+GKVHXWkeRccMxqdv/YFqOj14x7hiWfLsdt2DBmgMUxoUUHojqbIq2Ge/mqQSLjD3aM7GGBIbanYT4v/cUQpgQbfbd4fBEyleZvXyPbcnILmYe3X5PBP0pBIO2ZAOINfRXfXaGzB7E+XFCRnRe+eEsnt1atp8wwoy9Cv3JoWmryR2bPxK8lKDChrMOfwRkZO2ERgOU5gGD1lFiqZ4De449qO0FLKAC77HwQyNeroH5yqfctgCLUyyVuNQyxUaSNZ6tcWAk0bfTaL9vVS5JCuiP99ioJepEAYpP3178vEO0MmgEnT3R1j1M65vUMQb1g6ZUPxItALonCActsSLT88ufLodhlBcIRftjKuvDTo6590AkNwqeVPfxgEjTiTzEzdFJTPpZPFKlyphKrts4MHWWVf1CFh/qPDGPRJtnq69VgsKEMEj8a3T1E80plN/Jk2ZUmXYexKLm3Apjcf9Z7QiCm8XwqLcmDRp1i9cMD9PDPXjBe5TFD8pXeaEe05pEbDqvjYwufYoEUilQrqh8BEiqvU63zz679rh8XlhGQ3ygKHb9MQ2tdahJS6eoEtLkhoqiIFbOTG5mt1xKkIqxQr5JtoxG/Qv4+0K3hlVjNDry40=
  app: https://radiant-gorge-42464.herokuapp.com/
  on:
    repo: escottalexander/node-shopping-list-integration-tests
